// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	"go-zero/apps/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/wallpaper/captcha/get",
				Handler: getCaptchaHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/wallpaper/user/login",
				Handler: userLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/wallpaper/user/register",
				Handler: userRegisterHandler(serverCtx),
			},
		},
	)
}
