// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: user-rpc.proto

package admin

import (
	"context"

	"go-zero/apps/rpc/user/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdminFindPageReq      = user.AdminFindPageReq
	AdminFindPageResp     = user.AdminFindPageResp
	AdminFindUserPageReq  = user.AdminFindUserPageReq
	AdminFindUserPageResp = user.AdminFindUserPageResp
	ChangeUserStatusReq   = user.ChangeUserStatusReq
	CommonResp            = user.CommonResp
	InfoReq               = user.InfoReq
	InfoResp              = user.InfoResp
	LoginReq              = user.LoginReq
	LoginResp             = user.LoginResp
	RegisterReq           = user.RegisterReq
	RegisterResp          = user.RegisterResp

	Admin interface {
		FindPage(ctx context.Context, in *AdminFindPageReq, opts ...grpc.CallOption) (*AdminFindPageResp, error)
		FindUserPage(ctx context.Context, in *AdminFindUserPageReq, opts ...grpc.CallOption) (*AdminFindUserPageResp, error)
		ChangeUserStatus(ctx context.Context, in *ChangeUserStatusReq, opts ...grpc.CallOption) (*CommonResp, error)
	}

	defaultAdmin struct {
		cli zrpc.Client
	}
)

func NewAdmin(cli zrpc.Client) Admin {
	return &defaultAdmin{
		cli: cli,
	}
}

func (m *defaultAdmin) FindPage(ctx context.Context, in *AdminFindPageReq, opts ...grpc.CallOption) (*AdminFindPageResp, error) {
	client := user.NewAdminClient(m.cli.Conn())
	return client.FindPage(ctx, in, opts...)
}

func (m *defaultAdmin) FindUserPage(ctx context.Context, in *AdminFindUserPageReq, opts ...grpc.CallOption) (*AdminFindUserPageResp, error) {
	client := user.NewAdminClient(m.cli.Conn())
	return client.FindUserPage(ctx, in, opts...)
}

func (m *defaultAdmin) ChangeUserStatus(ctx context.Context, in *ChangeUserStatusReq, opts ...grpc.CallOption) (*CommonResp, error) {
	client := user.NewAdminClient(m.cli.Conn())
	return client.ChangeUserStatus(ctx, in, opts...)
}
