// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type GetCaptchaReq struct {
}

type Result struct {
}

type UserLoginReq struct {
	UserName     string `json:"userName"`
	UserPassword string `json:"userPassword"`
	//CaptchaCode  string `json:"captchaCode"`
}

type UserRegisterReq struct {
	UserName  string `json:"userName"`
	Password  string `json:"userPassword"`
	UserEmail string `json:"userEmail"`
	//CaptchaCode string `json:"captchaCode"`
}
