// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: user.proto

package server

import (
	"context"
	"go-zero/apps/user/rpc/internal/logic/register"
	"go-zero/apps/user/rpc/internal/svc"
	user2 "go-zero/apps/user/rpc/user"
)

type RegisterServer struct {
	svcCtx *svc.ServiceContext
	user2.UnimplementedRegisterServer
}

func NewRegisterServer(svcCtx *svc.ServiceContext) *RegisterServer {
	return &RegisterServer{
		svcCtx: svcCtx,
	}
}

func (s *RegisterServer) UserRegister(ctx context.Context, in *user2.RegisterReq) (*user2.RegisterResp, error) {
	l := registerlogic.registerlogic.NewUserRegisterLogic(ctx, s.svcCtx)
	return l.UserRegister(in)
}
