// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: user-rpc.proto

package other

import (
	"context"

	"go-zero/apps/rpc/user/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	InfoReq      = user.InfoReq
	InfoResp     = user.InfoResp
	LoginReq     = user.LoginReq
	LoginResp    = user.LoginResp
	RegisterReq  = user.RegisterReq
	RegisterResp = user.RegisterResp

	Other interface {
		UserInfo(ctx context.Context, in *InfoReq, opts ...grpc.CallOption) (*InfoResp, error)
	}

	defaultOther struct {
		cli zrpc.Client
	}
)

func NewOther(cli zrpc.Client) Other {
	return &defaultOther{
		cli: cli,
	}
}

func (m *defaultOther) UserInfo(ctx context.Context, in *InfoReq, opts ...grpc.CallOption) (*InfoResp, error) {
	client := user.NewOtherClient(m.cli.Conn())
	return client.UserInfo(ctx, in, opts...)
}
