// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: user.proto

package login

import (
	"context"
	user2 "go-zero/apps/user/rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	LoginReq     = user2.LoginReq
	LoginResp    = user2.LoginResp
	RegisterReq  = user2.RegisterReq
	RegisterResp = user2.RegisterResp

	Login interface {
		UserLogin(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
	}

	defaultLogin struct {
		cli zrpc.Client
	}
)

func NewLogin(cli zrpc.Client) Login {
	return &defaultLogin{
		cli: cli,
	}
}

func (m *defaultLogin) UserLogin(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := user2.NewLoginClient(m.cli.Conn())
	return client.UserLogin(ctx, in, opts...)
}
