// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: user-rpc.proto

package server

import (
	"context"

	"go-zero/apps/rpc/user/internal/logic/admin"
	"go-zero/apps/rpc/user/internal/svc"
	"go-zero/apps/rpc/user/user"
)

type AdminServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedAdminServer
}

func NewAdminServer(svcCtx *svc.ServiceContext) *AdminServer {
	return &AdminServer{
		svcCtx: svcCtx,
	}
}

func (s *AdminServer) FindPage(ctx context.Context, in *user.AdminFindPageReq) (*user.AdminFindPageResp, error) {
	l := adminlogic.NewFindPageLogic(ctx, s.svcCtx)
	return l.FindPage(in)
}

func (s *AdminServer) FindUserPage(ctx context.Context, in *user.AdminFindUserPageReq) (*user.AdminFindUserPageResp, error) {
	l := adminlogic.NewFindUserPageLogic(ctx, s.svcCtx)
	return l.FindUserPage(in)
}

func (s *AdminServer) ChangeUserStatus(ctx context.Context, in *user.ChangeUserStatusReq) (*user.CommonResp, error) {
	l := adminlogic.NewChangeUserStatusLogic(ctx, s.svcCtx)
	return l.ChangeUserStatus(in)
}
