// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: user-rpc.proto

package server

import (
	"context"

	"go-zero/apps/rpc/user/internal/logic/user"
	"go-zero/apps/rpc/user/internal/svc"
	"go-zero/apps/rpc/user/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) UserLogin(ctx context.Context, in *user.LoginReq) (*user.LoginResp, error) {
	l := userlogic.NewUserLoginLogic(ctx, s.svcCtx)
	return l.UserLogin(in)
}

func (s *UserServer) UserRegister(ctx context.Context, in *user.RegisterReq) (*user.RegisterResp, error) {
	l := userlogic.NewUserRegisterLogic(ctx, s.svcCtx)
	return l.UserRegister(in)
}

func (s *UserServer) UserInfo(ctx context.Context, in *user.InfoReq) (*user.InfoResp, error) {
	l := userlogic.NewUserInfoLogic(ctx, s.svcCtx)
	return l.UserInfo(in)
}
