// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type DownloadFileReq struct {
	FileName string `form:"fileName"` // MinIO 中存储的文件键（文件名/路径）
}

type GetCaptchaReq struct {
}

type Result struct {
}

type UploadRequest struct {
}

type UserLoginReq struct {
	UserName     string `json:"userName"`
	UserPassword string `json:"userPassword"`
	CaptchaCode  string `json:"captchaCode"`
}

type UserRegisterReq struct {
	UserName    string `json:"userName"`
	Password    string `json:"userPassword"`
	UserEmail   string `json:"userEmail"`
	CaptchaCode string `json:"captchaCode"`
}

type FindByPageReq struct {
	Page int32 `form:"page"`
	Size int32 `form:"size"`
}

type FindPageByNameReq struct {
	Page int32  `form:"page"`
	Size int32  `form:"size"`
	Name string `form:"name"`
}

type FindPageByTagReq struct {
	Page  int32 `json:"page"`
	Size  int32 `json:"size"`
	TagId int32 `json:"tagId"`
}
