// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: user-rpc.proto

package server

import (
	"context"

	"go-zero/apps/rpc/user/internal/logic/other"
	"go-zero/apps/rpc/user/internal/svc"
	"go-zero/apps/rpc/user/user"
)

type OtherServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedOtherServer
}

func NewOtherServer(svcCtx *svc.ServiceContext) *OtherServer {
	return &OtherServer{
		svcCtx: svcCtx,
	}
}

func (s *OtherServer) UserInfo(ctx context.Context, in *user.InfoReq) (*user.InfoResp, error) {
	l := otherlogic.NewUserInfoLogic(ctx, s.svcCtx)
	return l.UserInfo(in)
}
