// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: user.proto

package server

import (
	"context"
	"go-zero/apps/user/rpc/internal/logic/login"
	"go-zero/apps/user/rpc/internal/svc"
	user2 "go-zero/apps/user/rpc/user"
)

type LoginServer struct {
	svcCtx *svc.ServiceContext
	user2.UnimplementedLoginServer
}

func NewLoginServer(svcCtx *svc.ServiceContext) *LoginServer {
	return &LoginServer{
		svcCtx: svcCtx,
	}
}

func (s *LoginServer) UserLogin(ctx context.Context, in *user2.LoginReq) (*user2.LoginResp, error) {
	l := loginlogic.loginlogic.NewUserLoginLogic(ctx, s.svcCtx)
	return l.UserLogin(in)
}
