// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: tag-rpc.proto

package server

import (
	"context"

	"go-zero/apps/rpc/tag/internal/logic/tag"
	"go-zero/apps/rpc/tag/internal/svc"
	"go-zero/apps/rpc/tag/tag"
)

type TagServer struct {
	svcCtx *svc.ServiceContext
	tag.UnimplementedTagServer
}

func NewTagServer(svcCtx *svc.ServiceContext) *TagServer {
	return &TagServer{
		svcCtx: svcCtx,
	}
}

func (s *TagServer) GetTags(ctx context.Context, in *tag.GetTagsReq) (*tag.GetTagsResp, error) {
	l := taglogic.NewGetTagsLogic(ctx, s.svcCtx)
	return l.GetTags(in)
}
