// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	file "go-zero/apps/api/gateway/internal/handler/file"
	public "go-zero/apps/api/gateway/internal/handler/public"
	user "go-zero/apps/api/gateway/internal/handler/user"
	"go-zero/apps/api/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/collect",
					Handler: file.CollectHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/delete",
					Handler: file.DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/download",
					Handler: file.DownloadHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/upload",
					Handler: file.UploadHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/user/page",
					Handler: file.FileUserPageHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/wallpaper/file"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/file/find/name",
				Handler: public.FindPageByNameHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/file/find/page",
				Handler: public.FindByPageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/file/tag/find/page",
				Handler: public.FindPageByTagHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/file/tag/tags",
				Handler: public.GetTagsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/captcha",
				Handler: public.GetCaptchaHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: public.UserLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: public.UserRegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/wallpaper"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.JwtAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/info",
					Handler: user.UserInfoHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/wallpaper/user"),
	)
}
