// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: user-rpc.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	UserPassword  string                 `protobuf:"bytes,2,opt,name=userPassword,proto3" json:"userPassword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_user_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *LoginReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *LoginReq) GetUserPassword() string {
	if x != nil {
		return x.UserPassword
	}
	return ""
}

type LoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResp) Reset() {
	*x = LoginResp{}
	mi := &file_user_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResp) ProtoMessage() {}

func (x *LoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResp.ProtoReflect.Descriptor instead.
func (*LoginResp) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	UserPassword  string                 `protobuf:"bytes,2,opt,name=userPassword,proto3" json:"userPassword,omitempty"`
	UserEmail     string                 `protobuf:"bytes,3,opt,name=userEmail,proto3" json:"userEmail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_user_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *RegisterReq) GetUserPassword() string {
	if x != nil {
		return x.UserPassword
	}
	return ""
}

func (x *RegisterReq) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

type RegisterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResp) Reset() {
	*x = RegisterResp{}
	mi := &file_user_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResp) ProtoMessage() {}

func (x *RegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResp.ProtoReflect.Descriptor instead.
func (*RegisterResp) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type InfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoReq) Reset() {
	*x = InfoReq{}
	mi := &file_user_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoReq) ProtoMessage() {}

func (x *InfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoReq.ProtoReflect.Descriptor instead.
func (*InfoReq) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *InfoReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type InfoResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserName       string                 `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	UserEmail      string                 `protobuf:"bytes,2,opt,name=userEmail,proto3" json:"userEmail,omitempty"`
	JoinDate       string                 `protobuf:"bytes,3,opt,name=joinDate,proto3" json:"joinDate,omitempty"`
	UserAvatar     string                 `protobuf:"bytes,4,opt,name=userAvatar,proto3" json:"userAvatar,omitempty"`
	UploadNumber   int64                  `protobuf:"varint,5,opt,name=uploadNumber,proto3" json:"uploadNumber,omitempty"`
	DownloadNumber int64                  `protobuf:"varint,6,opt,name=downloadNumber,proto3" json:"downloadNumber,omitempty"`
	CollectNumber  int64                  `protobuf:"varint,7,opt,name=collectNumber,proto3" json:"collectNumber,omitempty"`
	Role           string                 `protobuf:"bytes,8,opt,name=role,proto3" json:"role,omitempty"`
	Enable         int32                  `protobuf:"varint,9,opt,name=enable,proto3" json:"enable,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InfoResp) Reset() {
	*x = InfoResp{}
	mi := &file_user_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResp) ProtoMessage() {}

func (x *InfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResp.ProtoReflect.Descriptor instead.
func (*InfoResp) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *InfoResp) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *InfoResp) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *InfoResp) GetJoinDate() string {
	if x != nil {
		return x.JoinDate
	}
	return ""
}

func (x *InfoResp) GetUserAvatar() string {
	if x != nil {
		return x.UserAvatar
	}
	return ""
}

func (x *InfoResp) GetUploadNumber() int64 {
	if x != nil {
		return x.UploadNumber
	}
	return 0
}

func (x *InfoResp) GetDownloadNumber() int64 {
	if x != nil {
		return x.DownloadNumber
	}
	return 0
}

func (x *InfoResp) GetCollectNumber() int64 {
	if x != nil {
		return x.CollectNumber
	}
	return 0
}

func (x *InfoResp) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *InfoResp) GetEnable() int32 {
	if x != nil {
		return x.Enable
	}
	return 0
}

type AdminFindPageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Filter        string                 `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminFindPageReq) Reset() {
	*x = AdminFindPageReq{}
	mi := &file_user_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminFindPageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminFindPageReq) ProtoMessage() {}

func (x *AdminFindPageReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminFindPageReq.ProtoReflect.Descriptor instead.
func (*AdminFindPageReq) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *AdminFindPageReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AdminFindPageReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *AdminFindPageReq) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type AdminFindPageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       string                 `protobuf:"bytes,1,opt,name=records,proto3" json:"records,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Current       int32                  `protobuf:"varint,4,opt,name=current,proto3" json:"current,omitempty"`
	Pages         int32                  `protobuf:"varint,5,opt,name=pages,proto3" json:"pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminFindPageResp) Reset() {
	*x = AdminFindPageResp{}
	mi := &file_user_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminFindPageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminFindPageResp) ProtoMessage() {}

func (x *AdminFindPageResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminFindPageResp.ProtoReflect.Descriptor instead.
func (*AdminFindPageResp) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *AdminFindPageResp) GetRecords() string {
	if x != nil {
		return x.Records
	}
	return ""
}

func (x *AdminFindPageResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AdminFindPageResp) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *AdminFindPageResp) GetCurrent() int32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *AdminFindPageResp) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

type AdminFindUserPageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminFindUserPageReq) Reset() {
	*x = AdminFindUserPageReq{}
	mi := &file_user_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminFindUserPageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminFindUserPageReq) ProtoMessage() {}

func (x *AdminFindUserPageReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminFindUserPageReq.ProtoReflect.Descriptor instead.
func (*AdminFindUserPageReq) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *AdminFindUserPageReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AdminFindUserPageReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *AdminFindUserPageReq) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type AdminFindUserPageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       string                 `protobuf:"bytes,1,opt,name=records,proto3" json:"records,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Current       int32                  `protobuf:"varint,4,opt,name=current,proto3" json:"current,omitempty"`
	Pages         int32                  `protobuf:"varint,5,opt,name=pages,proto3" json:"pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminFindUserPageResp) Reset() {
	*x = AdminFindUserPageResp{}
	mi := &file_user_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminFindUserPageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminFindUserPageResp) ProtoMessage() {}

func (x *AdminFindUserPageResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminFindUserPageResp.ProtoReflect.Descriptor instead.
func (*AdminFindUserPageResp) Descriptor() ([]byte, []int) {
	return file_user_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *AdminFindUserPageResp) GetRecords() string {
	if x != nil {
		return x.Records
	}
	return ""
}

func (x *AdminFindUserPageResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AdminFindUserPageResp) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *AdminFindUserPageResp) GetCurrent() int32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *AdminFindUserPageResp) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

var File_user_rpc_proto protoreflect.FileDescriptor

const file_user_rpc_proto_rawDesc = "" +
	"\n" +
	"\x0euser-rpc.proto\x12\x04user\"J\n" +
	"\bLoginReq\x12\x1a\n" +
	"\buserName\x18\x01 \x01(\tR\buserName\x12\"\n" +
	"\fuserPassword\x18\x02 \x01(\tR\fuserPassword\"!\n" +
	"\tLoginResp\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"k\n" +
	"\vRegisterReq\x12\x1a\n" +
	"\buserName\x18\x01 \x01(\tR\buserName\x12\"\n" +
	"\fuserPassword\x18\x02 \x01(\tR\fuserPassword\x12\x1c\n" +
	"\tuserEmail\x18\x03 \x01(\tR\tuserEmail\"&\n" +
	"\fRegisterResp\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"!\n" +
	"\aInfoReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"\x9e\x02\n" +
	"\bInfoResp\x12\x1a\n" +
	"\buserName\x18\x01 \x01(\tR\buserName\x12\x1c\n" +
	"\tuserEmail\x18\x02 \x01(\tR\tuserEmail\x12\x1a\n" +
	"\bjoinDate\x18\x03 \x01(\tR\bjoinDate\x12\x1e\n" +
	"\n" +
	"userAvatar\x18\x04 \x01(\tR\n" +
	"userAvatar\x12\"\n" +
	"\fuploadNumber\x18\x05 \x01(\x03R\fuploadNumber\x12&\n" +
	"\x0edownloadNumber\x18\x06 \x01(\x03R\x0edownloadNumber\x12$\n" +
	"\rcollectNumber\x18\a \x01(\x03R\rcollectNumber\x12\x12\n" +
	"\x04role\x18\b \x01(\tR\x04role\x12\x16\n" +
	"\x06enable\x18\t \x01(\x05R\x06enable\"R\n" +
	"\x10AdminFindPageReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\"\x87\x01\n" +
	"\x11AdminFindPageResp\x12\x18\n" +
	"\arecords\x18\x01 \x01(\tR\arecords\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\x12\x18\n" +
	"\acurrent\x18\x04 \x01(\x05R\acurrent\x12\x14\n" +
	"\x05pages\x18\x05 \x01(\x05R\x05pages\"R\n" +
	"\x14AdminFindUserPageReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"\x8b\x01\n" +
	"\x15AdminFindUserPageResp\x12\x18\n" +
	"\arecords\x18\x01 \x01(\tR\arecords\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\x12\x18\n" +
	"\acurrent\x18\x04 \x01(\x05R\acurrent\x12\x14\n" +
	"\x05pages\x18\x05 \x01(\x05R\x05pages2\x96\x01\n" +
	"\x04user\x12,\n" +
	"\tUserLogin\x12\x0e.user.LoginReq\x1a\x0f.user.LoginResp\x125\n" +
	"\fUserRegister\x12\x11.user.RegisterReq\x1a\x12.user.RegisterResp\x12)\n" +
	"\bUserInfo\x12\r.user.InfoReq\x1a\x0e.user.InfoResp2\x8d\x01\n" +
	"\x05admin\x12;\n" +
	"\bFindPage\x12\x16.user.AdminFindPageReq\x1a\x17.user.AdminFindPageResp\x12G\n" +
	"\fFindUserPage\x12\x1a.user.AdminFindUserPageReq\x1a\x1b.user.AdminFindUserPageRespB\bZ\x06./userb\x06proto3"

var (
	file_user_rpc_proto_rawDescOnce sync.Once
	file_user_rpc_proto_rawDescData []byte
)

func file_user_rpc_proto_rawDescGZIP() []byte {
	file_user_rpc_proto_rawDescOnce.Do(func() {
		file_user_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_rpc_proto_rawDesc), len(file_user_rpc_proto_rawDesc)))
	})
	return file_user_rpc_proto_rawDescData
}

var file_user_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_user_rpc_proto_goTypes = []any{
	(*LoginReq)(nil),              // 0: user.LoginReq
	(*LoginResp)(nil),             // 1: user.LoginResp
	(*RegisterReq)(nil),           // 2: user.RegisterReq
	(*RegisterResp)(nil),          // 3: user.RegisterResp
	(*InfoReq)(nil),               // 4: user.InfoReq
	(*InfoResp)(nil),              // 5: user.InfoResp
	(*AdminFindPageReq)(nil),      // 6: user.AdminFindPageReq
	(*AdminFindPageResp)(nil),     // 7: user.AdminFindPageResp
	(*AdminFindUserPageReq)(nil),  // 8: user.AdminFindUserPageReq
	(*AdminFindUserPageResp)(nil), // 9: user.AdminFindUserPageResp
}
var file_user_rpc_proto_depIdxs = []int32{
	0, // 0: user.user.UserLogin:input_type -> user.LoginReq
	2, // 1: user.user.UserRegister:input_type -> user.RegisterReq
	4, // 2: user.user.UserInfo:input_type -> user.InfoReq
	6, // 3: user.admin.FindPage:input_type -> user.AdminFindPageReq
	8, // 4: user.admin.FindUserPage:input_type -> user.AdminFindUserPageReq
	1, // 5: user.user.UserLogin:output_type -> user.LoginResp
	3, // 6: user.user.UserRegister:output_type -> user.RegisterResp
	5, // 7: user.user.UserInfo:output_type -> user.InfoResp
	7, // 8: user.admin.FindPage:output_type -> user.AdminFindPageResp
	9, // 9: user.admin.FindUserPage:output_type -> user.AdminFindUserPageResp
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_rpc_proto_init() }
func file_user_rpc_proto_init() {
	if File_user_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_rpc_proto_rawDesc), len(file_user_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_user_rpc_proto_goTypes,
		DependencyIndexes: file_user_rpc_proto_depIdxs,
		MessageInfos:      file_user_rpc_proto_msgTypes,
	}.Build()
	File_user_rpc_proto = out.File
	file_user_rpc_proto_goTypes = nil
	file_user_rpc_proto_depIdxs = nil
}
