// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: file-rpc.proto

package fileupload

import (
	"context"
	file2 "go-zero/apps/rpc/file/file"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	UploadReq      = file2.UploadReq
	UploadResponse = file2.UploadResponse

	FileUpload interface {
		// 单请求上传（适合中小文件）
		UploadFile(ctx context.Context, in *UploadReq, opts ...grpc.CallOption) (*UploadResponse, error)
	}

	defaultFileUpload struct {
		cli zrpc.Client
	}
)

func NewFileUpload(cli zrpc.Client) FileUpload {
	return &defaultFileUpload{
		cli: cli,
	}
}

// 单请求上传（适合中小文件）
func (m *defaultFileUpload) UploadFile(ctx context.Context, in *UploadReq, opts ...grpc.CallOption) (*UploadResponse, error) {
	client := file2.NewFileUploadClient(m.cli.Conn())
	return client.UploadFile(ctx, in, opts...)
}
