// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"go-zero/apps/api/community/internal/handler/file"
	user2 "go-zero/apps/api/community/internal/handler/user"
	"go-zero/apps/api/community/internal/svc"
	"net/http"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CorsMiddleware, serverCtx.JwtAuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/upload",
					Handler: file.UploadHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/wallpaper/file"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CorsMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/captcha",
					Handler: user2.GetCaptchaHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/login",
					Handler: user2.UserLoginHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/register",
					Handler: user2.UserRegisterHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/wallpaper/user"),
	)
}
