// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: file-rpc.proto

package server

import (
	"context"

	"go-zero/apps/file/rpc/file"
	"go-zero/apps/file/rpc/internal/logic/fileuploadservice"
	"go-zero/apps/file/rpc/internal/svc"
)

type FileUploadServiceServer struct {
	svcCtx *svc.ServiceContext
	file.UnimplementedFileUploadServiceServer
}

func NewFileUploadServiceServer(svcCtx *svc.ServiceContext) *FileUploadServiceServer {
	return &FileUploadServiceServer{
		svcCtx: svcCtx,
	}
}

// 单请求上传（适合中小文件）
func (s *FileUploadServiceServer) UploadFile(ctx context.Context, in *file.UploadReq) (*file.UploadResponse, error) {
	l := fileuploadservicelogic.NewUploadFileLogic(ctx, s.svcCtx)
	return l.UploadFile(in)
}
