// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: file-rpc.proto

package server

import (
	"context"

	"go-zero/apps/file/rpc/file"
	"go-zero/apps/file/rpc/internal/logic/fileupload"
	"go-zero/apps/file/rpc/internal/svc"
)

type FileUploadServer struct {
	svcCtx *svc.ServiceContext
	file.UnimplementedFileUploadServer
}

func NewFileUploadServer(svcCtx *svc.ServiceContext) *FileUploadServer {
	return &FileUploadServer{
		svcCtx: svcCtx,
	}
}

// 单请求上传（适合中小文件）
func (s *FileUploadServer) UploadFile(ctx context.Context, in *file.UploadReq) (*file.UploadResponse, error) {
	l := fileuploadlogic.NewUploadFileLogic(ctx, s.svcCtx)
	return l.UploadFile(in)
}
